[project]
name = "firefly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "open-clip-torch",
    "torch>=2.6",
    "torchvision",
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
open-clip-torch = { path = "libs/open-clip", editable = true }
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
